# Assignment-3

This notebook contains the coding questions to test the proficiency in `Pandas` library in python.

### Date: 13th December, 2025

### Steps to solve and upload the assignment 

- Download the notebook in your local machine.
- Solve the questions in the notebook and save it.
- Rename the file as `Assignment-03-<your_name>_<your_surname>.ipynb`. For example if your name is Dipika Chopra then name the file as `Assignment-03-Dipika_Chopra.ipynb`.
- Upload the solved notebook in your github repo under the folder **Assignment-3**.
- Upload the solved notebook in the google drive location: https://drive.google.com/drive/folders/1mMtPeHCmsKQE8KxK_RmnFFkTPfo5RYNJ?usp=drive_link 
<h3><span style="color:red"> Deadline: 10th January, 2026 </span></h3>

Use the `population_by_county.csv` file in the folder to complete the tasks.

**NOTE: TRY TO DO ALL THE TASKS IN ONE LINE OF PANDAS CODE.**

In [2]:
import pandas as pd

#### 1. Import pandas and read in the `population_by_county.csv` file into a dataframe called `pop`.

In [6]:
# Write your code here

pop = pd.read_csv("population_by_county.csv")
pd.DataFrame(pop)

                County           State  2010Census  2017PopEstimate
0     Abbeville County  South Carolina       25417            24722
1        Acadia Parish       Louisiana       61773            62590
2      Accomack County        Virginia       33164            32545
3           Ada County           Idaho      392365           456849
4         Adair County            Iowa        7682             7054
...                ...             ...         ...              ...
3137       Yuma County         Arizona      195751           207534
3138       Yuma County        Colorado       10043            10075
3139     Zapata County           Texas       14018            14322
3140     Zavala County           Texas       11677            11948
3141    Ziebach County    South Dakota        2801             2756

[3142 rows x 4 columns]

#### 2. Show the head of the dataframe, Also show top 8 rows of the dataframe using head

In [7]:
# Write your code here

pop.head(8)

             County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054
5      Adair County        Kentucky       18656            19485
6      Adair County        Missouri       25607            25377
7      Adair County        Oklahoma       22683            21909

#### 3. What are the column names?

In [11]:
# Write your code here
pop.columns

Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='object')

#### 4. How many States are represented in this data set?  
<em>Note: the data includes the `District of Columbia`</em>

In [21]:
# Write your code here
pop['State'].count

<bound method Series.count of 0       South Carolina
1            Louisiana
2             Virginia
3                Idaho
4                 Iowa
             ...
3137           Arizona
3138          Colorado
3139             Texas
3140             Texas
3141      South Dakota
Name: State, Length: 3142, dtype: object>

#### 5. Get a list or array of all the states in the data set.

In [ ]:
# Write your code here

s = pop['State'].values
print(s)

['South Carolina' 'Louisiana' 'Virginia' ... 'Texas' 'Texas'
 'South Dakota']

#### 6. What are the five most common County names in the U.S.?

In [41]:
# Write your code here
pop['County'].value_counts().head(5)

County
Washington County    30
Jefferson County     25
Franklin County      24
Jackson County       23
Lincoln County       23
Name: count, dtype: int64

#### 7. What are the top 5 most populated Counties according to the 2010 Census?

In [33]:
# Write your code here

a = pop.sort_values(by = "2010Census", ascending= False)
a.head()

                  County       State  2010Census  2017PopEstimate
1713  Los Angeles County  California     9818605         10163507
628          Cook County    Illinois     5194675          5211263
1209       Harris County       Texas     4092459          4652980
1784     Maricopa County     Arizona     3817117          4307033
2501    San Diego County  California     3095313          3337685

#### 8. What are the top 5 most populated States according to the 2010 Census?

In [42]:
# Write your code here

a = pop.sort_values(by = "2010Census", ascending= False)
a.head()

                  County       State  2010Census  2017PopEstimate
1713  Los Angeles County  California     9818605         10163507
628          Cook County    Illinois     5194675          5211263
1209       Harris County       Texas     4092459          4652980
1784     Maricopa County     Arizona     3817117          4307033
2501    San Diego County  California     3095313          3337685

#### 9. How many Counties have 2010 populations greater than 1 million?

In [27]:
# Write your code here
d = pop['2010Census'] > 1000000
print(d)

0       False
1       False
2       False
3       False
4       False
        ...
3137    False
3138    False
3139    False
3140    False
3141    False
Name: 2010Census, Length: 3142, dtype: bool

#### 10. How many Counties don't have the word "County" in their name?

In [55]:
# Write your code here

s = pop['County']
s[~s.str.contains('County')]

1                    Acadia Parish
32          Aleutians East Borough
33      Aleutians West Census Area
36                 Alexandria city
50                    Allen Parish
                   ...
3071               Winchester city
3076                   Winn Parish
3104     Wrangell City and Borough
3116      Yakutat City and Borough
3136     Yukon-Koyukuk Census Area
Name: County, Length: 135, dtype: object

#### 11. Add a column that calculates the percent change between the 2010 Census and the 2017 Population Estimate

In [49]:
# Write your code here

pop['Change'] = pop['2010Census'] * pop['2017PopEstimate'] / 100
pop

,County,State,2010Census,2017PopEstimate,new_column,Change
0,Abbeville County,South Carolina,25417,24722,6.283591e+06,6.283591e+06
1,Acadia Parish,Louisiana,61773,62590,3.866372e+07,3.866372e+07
2,Accomack County,Virginia,33164,32545,1.079322e+07,1.079322e+07
3,Ada County,Idaho,392365,456849,1.792516e+09,1.792516e+09
4,Adair County,Iowa,7682,7054,5.418883e+05,5.418883e+05
...,...,...,...,...,...,...
3137,Yuma County,Arizona,195751,207534,4.062499e+08,4.062499e+08
3138,Yuma County,Colorado,10043,10075,1.011832e+06,1.011832e+06
3139,Zapata County,Texas,14018,14322,2.007658e+06,2.007658e+06
3140,Zavala County,Texas,11677,11948,1.395168e+06,1.395168e+06
3141,Ziebach County,South Dakota,2801,2756,7.719556e+04,7.719556e+04

#### 12. What States have the highest estimated percent change between the 2010 Census and the 2017 Population Estimate?

**NOTE:** This will take several lines of code, as it requires a recalculation of Percent Change.

In [ ]:
# Write your code here